### ISSUE TITLE
Add Client-sided "Sound effects" setting

### ISSUE THREAD

**Issue by Hubcapp** [RSCPlus/rscplus#36]

**Comment by thelegendofbrian** [comment]
Elaborate a bit on this. Would this be an option to enable new sound effects (perhaps taken from RS 04/05 era)?

**Comment by Hubcapp** [comment]
The option for whether or not sounds are enabled is determined by server opcode 240, the 3rd byte. Letting the server remember and control this setting is bad, because while watching replays, Sounds will be "randomly" enabled or disabled, depending on whether the user recording the replay at the time wanted them.

In order to not be surprised by PYOEUE CLANG CLANG CLANG PKKKGGHT while fast forwarding through replays, the RSC+ Client must be able to override the Server's remembered Sound effects setting.

**Comment by Hubcapp** [comment]
This was resolved, it's the "Override server's remembered audio on/off setting" option in the Audio tab.
