### ISSUE TITLE
Implement part of the old client 127 protocol for Account Creation and Password Recovery

### ISSUE THREAD

**Issue by Hubcapp** [RSCPlus/rscplus#41]
## Background information:

mudclient 127 from March 18th 2002 has more advanced Account Manangement than later versions of the client, such as the one that RSC+ is based on.

These Account Management features include:

- Account Creation
- Setting Account Recovery Questions
- Recovering an Account

I'm not sure precisely when these features were removed, but by mudclient 192 (April 8th 2004), the features are gone, and the client instructs the user to use the website instead.

## Objective:

It would be useful for private server use if these features were intact in the client, but RSC+ WILL NOT implement private server exclusive features. If this feature enters RSC+, it must behave identically to how it did in Client 127. This way, it is not a private server feature, it is just reintroducing past functionality, similar to the FPS counter already in RSC+.

This feature must look exactly like it did in Client 127, and the network protocol must be exactly the same as Client 127 (regarding opcode, packet structure, and encryption).

Here is some 127 deob code for the relevant packets to be implemented:

### Account creation (client opcode 2)
```java
this.conn.enter(2);
this.conn.short_put(version);
this.conn.long_put(DataUtil.encode_name(s));
this.conn.enc_cred_put(pass, id, this.exp, this.mod);
this.conn.int_put(seed());
this.conn.send();
this.conn.read();
int j = this.conn.read();
this.conn.close();
System.out.println("Newplayer response: " + j);
```

### Setting account recovery questions (client opcode 208)
```java
this.conn.enter(208);
for (int j1 = 0; j1 < 5; j1++) {
  String s2 = this.aStringArray975[j1];
  if ((s2 == null) || (s2.length() == 0))
    s2 = String.valueOf(j1 + 1);
  if (s2.length() > 50)
    s2 = s2.substring(0, 50);
  this.conn.byte_put(s2.length());
  this.conn.str_put(s2);
  this.conn.enc_cred_put(DataUtil.base47_encode(this.aClass6_966
      .text(this.anIntArray971[j1])), this.sess_id,
      this.RSA_EXP, this.RSA_MOD);
}

this.conn.exit();
```

### Using account recovery questions (client opcode 8)
```java 
this.conn.enter(8);
this.conn.long_put(DataUtil
    .encode_name(this.aString947));
this.conn.int_put(seed());
this.conn.enc_cred_put(new StringBuilder().append(s4)
    .append(s6).toString(), i1, this.RSA_EXP,
    this.RSA_MOD);
for (int k1 = 0; k1 < 5; k1++) {
  this.conn.enc_cred_put(DataUtil
      .base47_encode(this.lost_ui
          .text(this.anIntArray989[k1])), i1,
      this.RSA_EXP, this.RSA_MOD);
}
this.conn.send();
this.conn.read();
int l1 = this.conn.read();
System.out.println(new StringBuilder()
    .append("Recover response: ").append(l1)
    .toString());
if (l1 == 0) {
  this.ui_state = 2;
  status_text(
      "Sorry, recovery failed. You may try again in 1 hour",
      "");
  this.aBoolean976 = true;
  return;
}
if (l1 == 1) {
  this.ui_state = 2;
  status_text(
      "Your pass has been reset. You may now use the new pass to login",
      "");
  return;
}
this.ui_state = 2;
status_text("Recovery failed! Attempts exceeded?", "");
return;
```

## Challenges:

1. Although there is no client opcode 2 or client opcode 208 in the modern client, client opcode 8 is already `CLIENT_OPCODE_SEND_DUEL_SETTINGS`. Obviously there is no conflict on our side if the client just sending opcode 8 with all this "extra" data, but if a server were implementing the hybrid RSC127/RSC235 protocol we are looking to adapt here, they would have to write a small distinction to figure out which opcode 8 the client is talking about. It could be done either by seeing that there is no Player associated with the connection, or by checking if packet length is 4 bytes long or not (RSC235 client opcode 8 is always 4 bytes, and RSC127 client opcode 8 can never be 4 bytes). If it were not possible to distinguish the two opcodes, there would be a problem, but it works out.

2. RSC+ currently automatically skips the first screen of the client with this line of code here:

https://github.com/RSCPlus/rscplus/blob/398a7156de953909d08ac5768d400a765a3b9488/src/Game/Client.java#L457

This should probably have been an option in the first place. We skip this screen right now because:
a. After the removal of these Account Management options, the initial screen really serves no purpose.
b. Actually, it is a hindrance. Every time this screen is loaded, the saved Username and Password are cleared. And also it is an extra click before you get into the client.

![2020-10-09-162953_800x580_scrot](https://user-images.githubusercontent.com/1337967/95633266-eb83ae80-0a4c-11eb-936d-6a9c3220efaa.png)

This screen has been disabled in RSC+ since 2016 and all features of the client have been programmed assuming that it is skipped. The screen must be made functional again, it must be tested with replay compatibility (drag-n-drop & queue especially). It must actually be extended to work (currently, even if this one line of code is removed, the "Click here to login" button seems to be broken) and it must be extended further to implement the RSC127 interface.

3. Like all other things, this feature must be on a toggle. If the user desires to restore the original RSC+ functionality of always launching directly to login screen on start, that must be possible.

4. Furthermore, I would probably like it if this login screen is only shown at the beginning of client run. Once the user has "click here to login", the client should not show the screen again unless the user clicks "Cancel" or relaunches the client.

**Comment by Hubcapp** [comment]
I tested dragging a replay onto the client while at that "Click here to login" screen, and luckily, it seems to work properly, just going directly to replay. :p

**Comment by Hubcapp** [comment]
More information:

The FORGOT_PASSWORD opcode existed in mudclient 127. It is client opcode 4 there, which conflicts with CLIENT_CAST_ON_INVENTORY_ITEM in the 235 protocol.
https://github.com/hikilaka/mudclient_127/blob/master/src/mudclient.java#L1848

----

ALSO
I found out that there is indeed already a toggle on the "Click here to login" screen. It is under the Streaming & Privacy tab. "Save login information between logins (Requires restart)".

**Comment by lmsv-mx123** [comment]
Will be divided by 3 segments (feature updates) very likely
[] Account Creation - In progress - should be for testing release soonish
[] Setting Account Security & Recovery Questions - TODO
[] Account Recovery - TODO

**Comment by Hubcapp** [comment]
Account Creation has been implemented in #51

**Comment by lmsv-mx123** [comment]
Although was not present in the 127, would like to also get added the in-game option of "Change contact details", this game option was featured sometime between mudclient 127 and 204.

The relevant code block concerning protocol part would be like:
`String string = this.hL.e(this.hN);
String string2 = this.hL.e(this.hO);
String string3 = this.hL.e(this.hP);
String string4 = this.hL.e(this.hQ);

if (string != null && string.length() != 0 && string2 != null && string2.length() != 0 && string3 != null && string3.length() != 0 && string4 != null && string4.length() != 0) {
this.Y.a(253, 155);
this.Y.a(string.length());
this.Y.a(string);
this.Y.a(string2.length());
this.Y.a(string2);
this.Y.a(string3.length());
this.Y.a(string3);
this.Y.a(string4.length());
this.Y.a(string4);
this.Y.g();
this.bO.c();
this.hK = false;
return;
}
`

**Comment by lmsv-mx123** [comment]
To place in next, probably will also be good to have included a validation that was on new accounts, basically:

![image](https://user-images.githubusercontent.com/10690767/99321183-41f9bf00-283b-11eb-8523-f831590faa60.png)

**Comment by lmsv-mx123** [comment]
OPCODE 197 - Change recovery questions request (mudclient 127 & mudclient 175)
OPCODE 247 - Change contact details request (mudclient 175)

**Comment by Hubcapp** [comment]
client opcode 197 is "Decline Duel" in RSC235
client opcode 247 is "Take Ground Item" in RSC235

**Comment by lmsv-mx123** [comment]
Change password request is Opcode 25 (after doing preliminary client side validations)

public void send_cred(String user, String pass) {
		user = DataUtil.filter_str(user, 20);
		pass = DataUtil.filter_str(pass, 20);
		conn.enter(25);
		conn.enc_cred_put(user + pass, sess_id, exp, mod);
		conn.exit();
	}

**Comment by Hubcapp** [comment]
All that's left is RSC175 opcode 196, to cancel Account Recovery questions "If you do not remember making this request"

**Comment by Hubcapp** [comment]
luckily there is no RSC235 client opcode 196

**Comment by lmsv-mx123** [comment]
So here's my thoughts for the cancel Account recovery change, probably @Hubcapp can indicate better if wrong

* Server instructs with code welcomeRecoverySetDays = 201 if user has recovery questions set and they cannot be canceled (either as first time or time expired, i.e. 14 days or more)
* Code of welcomeRecoverySetDays = 200 is player has not set their recovery questions and gives the `You have not yet set any password recovery questions. [...] Do this from the \'account management\' area on our front webpage`. This wasn't a thing in RSC175 and previous (probably here we can just have trimmed the do this from the account management part
* Just by reading from the client it would seem that a number between 0 and 199 (inclusive) would have given (though very likely kept server side concept of more than 14 days then marked as permanent recovery questions

                this.surface.drawstringCenter(var4 + " you changed your recovery questions", 1, var3, 256, 0xff8000);
                var3 += 15;
                this.surface.drawstringCenter("If you do not remember making this change then cancel it immediately", 1, var3, 256, 0xff8000);
                var3 += 15;
                this.surface.drawstringCenter("Do this from the \'account management\' area on our front webpage", 1, var3, 256, 0xff8000);
                var3 += 15;

**Comment by lmsv-mx123** [comment]
All good to go for this issue, follow-up for any possible enhancements will be in #62
