### ISSUE TITLE
Use original font rendering method more places (or at least give option...)

### ISSUE THREAD

**Issue by Hubcapp** [RSCPlus/rscplus#45]
Several places, RSC+ draws text on the game window using its own font. If we used the same method that the retro FPS counter uses to draw text, it might look nicer.

* Satchel inventory space count
* Hits/Prayer/Fatigue display in top left
* XP Bar

**Comment by conker-rsc** [comment]
@Hubcapp this can probably be closed out now with the completion of #157?
