### ISSUE TITLE
Sell X to general store can crash client in very specific circumstance

### ISSUE THREAD

**Issue by Hubcapp** [RSCPlus/rscplus#64]
Steps to reproduce:

1. Sell an item to a general store that it does not usually stock
2. Click the item that you have sold to the store and select "Sell X"
3. Wait for the store to naturally despawn the sold items 
4. Submit your request to Sell the item to the shop
5. The game loses the reference to the item since it has despawned from the shop's inventory and so
```
[  GAME][05:31:27] Error: client.PB(-43) client.DC(0) client.AB(13) client.JD(false) | client.c client.I client.f client.b e.run java.lang.Thread.run:745 | java.lang.ArrayIndexOutOfBoundsException: -1
[  GAME][05:31:27] error_game_crash
```

**Comment by Hubcapp** [comment]
Possibly related to #50

**Comment by lmsv-mx123** [comment]
applies to also when Buying X probably
