### ISSUE TITLE
XP bar blocks clicks even when it is turned off in options

### ISSUE THREAD

**Issue by aldrichdev** [RSCPlus/rscplus#94]
I was noticing a dead click (specifically right-clicking) in the area circled in red, but only after killing an NPC, and for a short time - then right click works again. Seems like it might be the XB bar intercepting the click, even though it's not visible

![image](https://media.discordapp.net/attachments/695695687828111470/933601933149732874/unknown.png)

**Comment by Hubcapp** [comment]
resolved by #95
