### ISSUE TITLE
Prevent sleepwords from being sent over private chat

### ISSUE THREAD

**Issue by Hubcapp** [RSCPlus/rscplus#96]
There is a bug in the base RSC client.

1. Click on bed.
2. Click on friend's name before sleeping interface opens.
3. The entered captcha in sleeping interface will be also sent to the friend in a private message.

Likely the sleeping interface needs to consume keypress.

**Comment by lmsv-mx123** [comment]
It does not work on cosuming or not keypress sadly, however the solution is to prevent from adding characters to the input that would be used to send private message

**Comment by lmsv-mx123** [comment]
On examining & trying to implement solution using injection it is more complex than that but with codebase think can come with something
